### ISSUE TITLE
Upgrade to docker compose v2

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8781]
**Describe the issue**

In a few places in our code and documentation we use the `docker-compose` command (NB: with hyphen) which is the v1 version of the command. v1 has been deprecated in favour of v2 which uses `docker compose` (NB: with space).

**Describe the improvement you'd like**

Update the code and the dev environment setup docs to specify v2 use.

**Describe alternatives you've considered**

You can just alias the hyphen version to the non-hyphen version but that's an additional unnecessary install step.

**Comment by lorerod** [comment]
Hi @gareth, I was planning on starting work on this issue and found [this](https://github.com/medic/cht-core/tree/8781-update-docker) branch. Can I continue the work you already started there? I would love to know your thoughts.

**Comment by garethbowen** [comment]
@lorerod Yes! Please. I got a bit stuck as you can see but I'm happy to hand over to you. It's a bit out of date so if it's too hard to rebase you can just start a new one and patch some of the ideas over. The only thing to be aware of is we're gradually shifting off docker compose, [starting with CI](https://github.com/medic/cht-core/issues/8909), which might mean some of this work isn't needed. @dianabarsan Is the plan eventually to remove docker compose from all e2e testing (including local)?

**Comment by dianabarsan** [comment]
I think it's a pain to run things over K3D, especially locally. I think we should change CI e2e tests to run over our chosen prod architecture. Having to support both docker compose _and_ k3d in our e2e tests might be annoying, especially if we end up never running CI tests over docker. 

A significant amount of changes are coming with the addition of k3d, especially on how we run commands. 
I think we should wait for that to land (I'm hoping this is quite soon, I'm just getting the last details in), and then start working on migrating to `docker compose`.

**Comment by garethbowen** [comment]
This should now be resolved in cht-core. There are however many references to `docker-compose` in cht-docs, and possibly cht-conf and other repos that we should resolve too.

**Comment by lorerod** [comment]
Also, docker helper scripts need to be updated.

**Comment by mrjones-plip** [comment]
Note that Helper should be fixed in https://github.com/medic/cht-core/pull/9309

**Comment by garethbowen** [comment]
@mrjones-plip I think this is now complete. Do you know of any outstanding work or should we close this off?

**Comment by mrjones-plip** [comment]
There's two areas I still see:
* cht 3.x docker compose [script](https://github.com/medic/cht-core/blob/master/scripts/docker-helper/cht-docker-compose.sh#L189)
* a few lingering [instances in docs](https://github.com/search?q=repo%3Amedic%2Fcht-docs%20%22docker-compose%20%22&type=code), including about 3.x helper

I'll try and clean those up next week!

**Comment by garethbowen** [comment]
No hurry! Thanks for the update.
