### ISSUE TITLE
UI Nav Work Image Replacement - Feature Targets

### ISSUE THREAD

**Issue by lorerod** [medic/cht-core#9503]
Cover the UI navigation image updates and start generating screenshots for that work based on the [Google doc shared](https://docs.google.com/document/d/1MHOynkEhWU63TMJo4x8JCuJDapjBk1LW3OnjTXXhi0c/edit#heading=h.ou7i848wdrk1).

This issue will cover the images for:
[Targets](https://docs.communityhealthtoolkit.org/building/features/targets/)

- [ ] Targets full page - mobile & desktop view
- [ ] Count and percentage widgets

**Comment by dhruv11pat** [comment]
hi @lorerod, during the local development setup when i am using the command 'cd ~/cht-core && npm run build-dev-watch'
i am facing an error saying '.' is not recognized as an internal or external command. Can you help me out here?

<img width="920" alt="Image" src="https://github.com/user-attachments/assets/fc987a98-d951-4bd2-be8c-9fbcd276784b" />

**Comment by dhruv11pat** [comment]
hi @lorerod, I have a doubt when we start contributing we fork the repository and then clone it and make a branch and then do some changes in the code. But in the local setup development documentation, we clone the main cht-core repository if we want to change the in vs-code how will it affect the one which is running locally(both of then are in different folders).

**Comment by dhruv11pat** [comment]
hi @andrablaj, i am working on this issue. Is this assigned to me? As i cannot see in the assigned section of CHT Community Contributions.

**Comment by dhruv11pat** [comment]
hi @andrablaj,can you help me here? i followed the local creation of app instance i am not able to resolve this error i also followed the course.

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/c73d6c3a-d008-4f4a-9c2e-48f7596e6f20" />

**Comment by andrablaj** [comment]
Hi @dhruv11pat! Thank you for your interest in contributing. @lorerod should be able to support you once she is back online, or redirect you to the [forum](https://forum.communityhealthtoolkit.org/) if your error needs more conversation.

**Comment by lorerod** [comment]
> hi @andrablaj,can you help me here? i followed the local creation of app instance i am not able to resolve this error i also followed the course.

Hi @dhruv11pat!
Sorry you’re running into this issue. To help us troubleshoot, could you please share a bit more about your setup?

- What operating system are you using (Windows, macOS, Linux)?
- If you’re on Windows, are you using Git Bash, WSL, or another terminal?
- Could you also share the contents of your generated .env file (removing any sensitive info like passwords)?

Looping in @mrjones as well, since he may have encountered this issue before and might have some additional insights.
Thanks for your patience—we’ll get this sorted out!

Also, just a heads up:
There’s no need to have the CHT instance running when you run `npm run wdio-visual-desktop` to execute the tests. This command automatically sets up its own test environment with Docker containers. If you have your dev environment running at the same time, it can actually cause conflicts.

**Comment by dhruv11pat** [comment]
Thanks @lorerod , I am using git bash in windows and I have solved the issue.

**Comment by mrjones-plip** [comment]
Great to hear you solved the issue @dhruv11pat !  Could you update us with the fix to your issue?  It's always nice when others have the same issue to see the fix instead of [being stranded](https://xkcd.com/979/).  Thanks!

**Comment by dhruv11pat** [comment]
Yes @mrjones-plip, there was an error in my .env file at line 6. This was fixed by putting that variable in the double quotes ("") so it can be read as string. Same was applied to line 10 and 11.

<img width="914" alt="Image" src="https://github.com/user-attachments/assets/cd5ec910-48c7-4293-a497-c4556b0cf008" />

**Comment by dhruv11pat** [comment]
hi  @mrjones-plip @lorerod , can you help me out here I am getting this error while running the command npm run wdio-visual-desktop in git-bash

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/c761125d-ddc3-4e36-b4d3-0162ebc5605c" />

**Comment by dhruv11pat** [comment]
Hi @mrjones-plipYes @lorerod, I am not able post anything in forum. I dont know why i am given read only access. Can you check it out?

**Comment by dhruv11pat** [comment]
Yes, it's working. Thanks @andrablaj.

**Comment by lorerod** [comment]
Hi @dhruv11pat, I'm sorry you still encounter blockers for this work. You mentioned [in a previous message](https://github.com/medic/cht-core/issues/9503#issuecomment-2836394871) that you are using Git Bash on Windows. The issue could be because the `export` command is not recognized in the Windows environment. 
To resolve this, you can try one of these approaches:
1. In Git Bash, remove the `export` keyword and run:
`VERSION=$(node ./scripts/build/get-version.js) && ./scripts/build/build-service-images.sh && wdio run ./tests/e2e/visual/wdio.conf.js --suite=desktopTests` 
2. Alternatively, you might want to consider using Windows Subsystem for Linux (WSL), which provides a Linux environment on Windows.

Let us know if you need help with either of these approaches or if you run into any other issues!

**Comment by dhruv11pat** [comment]
Thanks @lorerod , I used WSL and it worked.

**Comment by not-kenneth** [comment]
Hi there, I'm Kenneth from Edify. Could you assign this ticket to me? Thanks!

**Comment by lorerod** [comment]
Hi @not-kenneth, thank you for your interest here!. This issue has two sub-issues. The first one is already completed. Could you please comment on the second one: [Targets widgets](https://github.com/medic/cht-core/issues/9927) so I can assign it to you?
